### ISSUE TITLE
Java Thread Affinity exception for Mac OS X (ExceptionInInitializerError)

### ISSUE THREAD

**Issue by cballock** [OpenHFT/Java-Thread-Affinity#25]
Hi, Peter. I am experiencing an exception when trying to use Java Thread Affinity in my Mac OS X (stack below):

Exception in thread "main" java.lang.ExceptionInInitializerError
	at Main.recursion(Main.java:46)
	at Main.main(Main.java:23)
Caused by: java.lang.NullPointerException
	at java.util.BitSet.and(BitSet.java:916)
	at net.openhft.affinity.AffinityLock.getReservedAffinity0(AffinityLock.java:113)
	at net.openhft.affinity.AffinityLock.<clinit>(AffinityLock.java:46)
	... 2 more 

Debugging your code I have noticed that the method getAffinity() in class OSXJNAAffinity always return null and that is what is causing that exception. Please, can you confirm that? If so, how can I use your library in Mac?

Thank you.

My environment:
- Affinity version: 3.0; 
- SO: Mac OS X Yosemite;
-  Java version: 1.8.0_65;

**Comment by lburgazzoli** [comment]
Can you please provide all the dependencies you have and a snippet showing the exception?

**Comment by cballock** [comment]
The full exception stack I've got is this:

Exception in thread "main" java.lang.ExceptionInInitializerError
at Main.recursion(Main.java:46)
at Main.main(Main.java:23)
Caused by: java.lang.NullPointerException
at java.util.BitSet.and(BitSet.java:916)
at net.openhft.affinity.AffinityLock.getReservedAffinity0(AffinityLock.java:113)
at net.openhft.affinity.AffinityLock.(AffinityLock.java:46)
... 2 more

All my dependencies are the following:

- affinity-3.0.jar
- jna-4.2.1.jar
- jna-platform-4.2.1.jar
- slf4j-api-1.7.13.jar
- slf4j-nop-1.7.13.jar

**Comment by cballock** [comment]
My class:

import net.openhft.affinity.AffinityLock;

public class Main {

	public static final void main(String[] args) throws Exception {
		
		System.out.println("OS: " + System.getProperty("os.name"));
		System.out.println("Processors: " + Runtime.getRuntime().availableProcessors());
		
		int max = 10000;
		
		long nanos = System.nanoTime();
		Integer result = sum(max);
		nanos = System.nanoTime() - nanos;
		
		System.out.println("Result: " + result);
		System.out.println("Nanos: " + nanos);
	}
	
	public static int sum(int max) throws InterruptedException {
		
		try (AffinityLock lock1 = AffinityLock.acquireLock()) {
			int sum = 0;
			for(int i=0; i<max; i++) {
				sum += i;
			}
			return sum;
		}
	}
}

The output:

OS: Mac OS X
Processors: 4
Exception in thread "main" java.lang.ExceptionInInitializerError
	at Main.sum(Main.java:22)
	at Main.main(Main.java:13)
Caused by: java.lang.NullPointerException
	at java.util.BitSet.and(BitSet.java:916)
	at net.openhft.affinity.AffinityLock.getReservedAffinity0(AffinityLock.java:113)
	at net.openhft.affinity.AffinityLock.<clinit>(AffinityLock.java:46)
	... 2 more

**Comment by lburgazzoli** [comment]
Looks like this bug has been solved in 3.0.1-SNAPSHOT you can grab from [Sonatype OSS](https://oss.sonatype.org/content/repositories/snapshots)

However thread affinity on OSX may not work as expected:

```
OS X does not export interfaces that identify processors or control thread placement—explicit thread
to processor binding is not supported. Instead, the kernel manages all thread placement. 
Applications expect that the scheduler will, under most circumstances, run its threads using a good
processor placement with respect to cache affinity.
```

Taken from [Apple Affinity API](https://developer.apple.com/library/mac/releasenotes/Performance/RN-AffinityAPI)

**Comment by cballock** [comment]
Thank you for your response. But I couldn't find the 3.0.1-SNAPSHOT in the Sonatype OSS (https://oss.sonatype.org/content/repositories/snapshots/net/openhft/Java-Thread-Affinity/). Please, can you confirm the repository url?

**Comment by lburgazzoli** [comment]
Artifact is affinity so net/openhft/affinity

On Monday, 28 December 2015, cballock <notifications@github.com> wrote:

> Thank you for your response. But I couldn't find the 3.0.1-SNAPSHOT in the
> Sonatype OSS (
> https://oss.sonatype.org/content/repositories/snapshots/net/openhft/Java-Thread-Affinity/).
> Please, can you confirm the repository url?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenHFT/Java-Thread-Affinity/issues/25#issuecomment-167621441>
> .
>


-- 
lb

**Comment by cballock** [comment]
I've tried with the latest version but the problem still occurs. I've also inspected the method getAffinity() in class OSXJNAAffinity in that version and it always returns null. For me, it seems that this is the cause of my exception.

**Comment by lburgazzoli** [comment]
Latest 3.0.1-SNAPSHOT ?

**Comment by cballock** [comment]
Sorry, I've tested with version 3.1, not 3.0.1. Now it works. Thank you very much!

**Comment by tckb** [comment]
is this currently supported in macOS? looks like it doesn't. I ran the same program as @cballock , here's my output. 
```
OS: Mac OS X
Processors: 4
Using MAC OSX JNA-based thread id implementation
cpu 0 base=0 reservable= false
cpu 1 base=1 reservable= false
cpu 2 base=2 reservable= false
cpu 3 base=3 reservable= false
Assigning cpu 3 to Thread[main,5,main]
unable to set mask to 8 as the JNIa nd JNA libraries and not loaded
Releasing cpu 3 from Thread[main,5,main]
unable to set mask to  as the JNIa nd JNA libraries and not loaded
Result: 49995000
Nanos: 1115497718
```
Here are my dependencies:

```
java: 1.8.0_102
affinity - 3.1.6
jna-platform - 4.5.1
jna - 4.1.0
```


@peter-lawrey  can you weigh in?

**Comment by RobAustin** [comment]
@cballock I do chronicle development using a mac, and yes it was also my understanding that the this library does not work on the mac.

**Comment by tckb** [comment]
@RobAustin  assuming it's addressed to me :) , was there any specific reason it's not supported anymore? the original repo from @peter-lawrey  had some traction on osx.

**Comment by RobAustin** [comment]
@tckb we have not do the work to get it working on the mac

**Comment by RobAustin** [comment]
@tckb are you you able to fix/implement the osx implementation ?

**Comment by tckb** [comment]
@RobAustin  I am not sure, I've just started looking into it. will update it if I can find any reasonable solution.

**Comment by RobAustin** [comment]
@tckb if you are able to ( please issue a pull request ) and we can merge in your changes.

**Comment by sunxien** [comment]
Ask another question about affinity run on MacOSX:

![image](https://github.com/OpenHFT/Java-Thread-Affinity/assets/81640257/05c4612e-7b39-4eb7-9124-0661ebccc569)

Why CPU Usage that was shew on Terminal and Monitor Window are different?

**Comment by alamar** [comment]
@sunxien It is likely that CPU0 + CPU2 + CPU4 + CPU6 + CPU8 + CPU10 = 1.0 in your case - Terminal is running what I assume is `top` which can show 100% load per core, meaning it could go all the way towards 1200% in your case. Right now you are only using one core fully, just distributed between even numbered cores. All of these stacks would likely add up to one full bar.
